### ISSUE TITLE
Invalid configuration for content while running below code 

### ISSUE THREAD

**Issue by mravitej** [svanoort/pyresttest#251]
I didn't figure out the issue could someone please help me out

- config:
    - testset: "Api tests"
    # Variables to use in the test set
    - variable_binds: {user_id: "ravitej", pass: "123456"}
- test: #Project_Admin: User Login success
    - name: "Project_Admin: User login success"
    - url: "/user/login"
    - method: "POST"
    - body: {template: {"username": "$user_id", "password": "$pass", "authtype": "plain"}}
    - headers: {Content-Type: application/json}
    - expected_status: [200]
    - group: "Login_User"

output:
Traceback (most recent call last):
  File "/usr/local/bin/pyresttest", line 5, in <module>
    pkg_resources.run_script('pyresttest==1.7.2.dev', 'pyresttest')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/pyresttest-1.7.2.dev-py2.7.egg/EGG-INFO/scripts/pyresttest", line 4, in <module>
    resttest.command_line_run(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/pyresttest-1.7.2.dev-py2.7.egg/pyresttest/resttest.py", line 1090, in command_line_run
    main(args)
  File "/usr/local/lib/python2.7/dist-packages/pyresttest-1.7.2.dev-py2.7.egg/pyresttest/resttest.py", line 1009, in main
    working_directory=os.path.dirname(test_file), vars=my_vars)
  File "/usr/local/lib/python2.7/dist-packages/pyresttest-1.7.2.dev-py2.7.egg/pyresttest/resttest.py", line 255, in parse_testsets
    mytest = Test.parse_test(base_url, child)
  File "/usr/local/lib/python2.7/dist-packages/pyresttest-1.7.2.dev-py2.7.egg/pyresttest/tests.py", line 461, in parse_test
    if use_config_parser(mytest, configelement, configvalue):
  File "/usr/local/lib/python2.7/dist-packages/pyresttest-1.7.2.dev-py2.7.egg/pyresttest/tests.py", line 454, in use_config_parser
    converted = myparsing[0](configvalue)
  File "/usr/local/lib/python2.7/dist-packages/pyresttest-1.7.2.dev-py2.7.egg/pyresttest/contenthandling.py", line 148, in parse_content
    raise Exception("Invalid configuration for content.")
Exception: Invalid configuration for content.

**Comment by mvitiuk** [comment]
I have it like this:
    - variable_binds: {
          **'cache'**: 'Cache-Control', 'cachevalue': 'no-cache',
          'content_type': 'Content-Type', 'content_type_value': 'application/json',
      }

    - headers: {template: {'$content_type': '$content_type_value', '$cache': '$cachevalue'}}

don't know is it matters or not, but my variables are inside **'value'**
