### ISSUE TITLE
Pyresttest reports Exception: No valid extractor name to use in input

### ISSUE THREAD

**Issue by compelling** [svanoort/pyresttest#260]
When I try to use jmespath after a clean install I get, "Exception: No valid extractor name to use in input". 
It seems pyresttest is using Python 2.7
`Traceback (most recent call last):

  File "/usr/local/bin/pyresttest", line 4, in <module>
    __import__('pkg_resources').run_script('pyresttest==1.7.2.dev0', 'pyresttest')

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
`
Jmespath seems to be installed for Python 2.7:
`$ easy_install jmespath

Searching for jmespath

Best match: jmespath 0.9.3

Processing jmespath-0.9.3-py2.7.egg

jmespath 0.9.3 is already the active version in easy-install.pth

Installing jp.py script to /usr/local/bin

Using /usr/local/lib/python2.7/site-packages/jmespath-0.9.3-py2.7.egg

Processing dependencies for jmespath

Finished processing dependencies for jmespath`

**Comment by yelfathi** [comment]
Hi I have the same issue, either using jmespath or json_mini:

```
Traceback (most recent call last):
  File "/usr/local/bin/resttest.py", line 4, in <module>
    resttest.command_line_run(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/pyresttest/resttest.py", line 911, in command_line_run
    main(args)
  File "/usr/local/lib/python2.7/dist-packages/pyresttest/resttest.py", line 830, in main
    working_directory=os.path.dirname(test_file), vars=my_vars)
  File "/usr/local/lib/python2.7/dist-packages/pyresttest/resttest.py", line 252, in parse_testsets
    mytest = Test.parse_test(base_url, child)
  File "/usr/local/lib/python2.7/dist-packages/pyresttest/tests.py", line 512, in parse_test
    validator_type, validator_config)
  File "/usr/local/lib/python2.7/dist-packages/pyresttest/validators.py", line 530, in parse_validator
    valid = VALIDATORS[name](config_node)
  File "/usr/local/lib/python2.7/dist-packages/pyresttest/validators.py", line 444, in parse
    output.expected = _get_extractor(expected)
  File "/usr/local/lib/python2.7/dist-packages/pyresttest/validators.py", line 318, in _get_extractor
    'No valid extractor name to use in input: {0}'.format(config_dict))
Exception: No valid extractor name to use in input: {'in-sync': False}`
```

JSON:

```
{
    "qos:output": {
        "in-sync": false
    }
}
```

Validator:

```
- compare: {jsonpath_mini: "qos:output", comparator: "eq", expected: {"in-sync": false}}
```

**Comment by Anjimeduri** [comment]
pip3 install Jmespath
